// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhewwiaiitgrkqqviews.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZXd3aWFpaXRncmtxcXZpZXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDUyMjksImV4cCI6MjA2ODI4MTIyOX0.MBEHn-JnP6YVqwEPv92uMmXuPCNKecDYx66_BVvxt9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});